### PR TITLE
Add Kubernetes deployment and service files

### PR DESCRIPTION
**Pull request by victorgrubio**

### CODE REVIEW

**Comment by victorgrubio** [comment]
For future reference on local postgres: https://www.airplane.dev/blog/deploy-postgres-on-kubernetes

**Comment by victorgrubio** [comment]
@kovaj024 Is it ready for review?

**Comment by kovaj024** [comment]
@victorgrubio I don't think so

**Comment by victorgrubio** [comment]
Ping me whenver you have successfully tested it. Please upload a screenshot of it working on your laptop showing nodeport address. Let me know if you need additional help :)

**Comment by victorgrubio** [comment]
@kovaj024 Should I merge this one?

**Comment by kovaj024** [comment]
> @kovaj024 Should I merge this one?

sure

**Review by victorgrubio — COMMENTED** [review]
LGTM, great job!

**Pull request merged**
